# Generated by Django 4.1.4 on 2023-01-02 10:45

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=tinymce.models.HTMLField(null=True, verbose_name='Description'),
        ),
    ]
