# Generated by Django 4.1.4 on 2023-01-04 09:56

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='advantages',
            field=tinymce.models.HTMLField(verbose_name='Advantages'),
        ),
    ]
