# Generated by Django 4.1.4 on 2022-12-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='products_images/', verbose_name='Image')),
                ('title', models.CharField(max_length=200, verbose_name='Header')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='New price')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Old price')),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider', 'verbose_name_plural': 'Slider'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='images',
            field=models.ImageField(upload_to='slider_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Header'),
        ),
    ]
