# Generated by Django 4.1.4 on 2022-12-21 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_products_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.products', verbose_name='Best Product')),
            ],
            options={
                'verbose_name': 'Best Product',
                'verbose_name_plural': 'Best Products',
            },
        ),
    ]
