# Generated by Django 4.1.4 on 2022-12-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_bestproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
