# Generated by Django 4.1.4 on 2022-12-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestproduct',
            name='end_of_discount',
            field=models.DateField(null=True),
        ),
    ]
