# Generated by Django 4.1.4 on 2022-12-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_bestproduct_end_of_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('images', models.ImageField(upload_to='comments_home_images/', verbose_name='Photo')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('profession', models.CharField(max_length=150, verbose_name='Profession')),
            ],
            options={
                'verbose_name': 'Comment Home',
                'verbose_name_plural': 'Comment Home',
            },
        ),
    ]
