# Generated by Django 4.1.4 on 2022-12-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_commentshome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
