# Generated by Django 4.1.4 on 2022-12-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_products_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
    ]
