# Generated by Django 4.1.4 on 2022-12-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_remove_products_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Availability')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Color')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='long_description',
            field=models.TextField(null=True, verbose_name='Full description'),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='products',
            name='vendor_code',
            field=models.CharField(max_length=255, null=True, verbose_name='Vendor Code'),
        ),
        migrations.AddField(
            model_name='products',
            name='availability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.availability', verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.color', verbose_name='Color'),
        ),
    ]
