# Generated by Django 4.1.4 on 2022-12-22 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_availability_color_products_long_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='description',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='images',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
        migrations.AddField(
            model_name='slider',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.products', verbose_name='Product Slider'),
        ),
    ]
