# Generated by Django 4.1.4 on 2022-12-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_remove_slider_description_remove_slider_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True, verbose_name='Url'),
        ),
    ]
