# Generated by Django 4.1.4 on 2022-12-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=100, verbose_name='Length')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='Size')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ManyToManyField(null=True, to='food.brand'),
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='length',
            field=models.ManyToManyField(null=True, to='food.length'),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(null=True, to='food.size'),
        ),
    ]
