# Generated by Django 4.1.4 on 2022-12-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_length_size_products_brand_products_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ManyToManyField(to='food.brand'),
        ),
        migrations.AlterField(
            model_name='products',
            name='length',
            field=models.ManyToManyField(to='food.length'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(to='food.size'),
        ),
    ]
