# Generated by Django 4.1.4 on 2022-12-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_alter_products_brand_alter_products_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='products',
            name='length',
        ),
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.DeleteModel(
            name='Length',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
