# Generated by Django 4.1.4 on 2022-12-23 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_remove_products_brand_remove_products_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.color', verbose_name='Color'),
        ),
    ]
