# Generated by Django 4.1.4 on 2022-12-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_remove_products_color_products_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
    ]
