# Generated by Django 4.1.4 on 2022-12-23 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_remove_products_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.color'),
        ),
    ]
