# Generated by Django 4.1.4 on 2022-12-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0023_products_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='test',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=200, null=True),
        ),
    ]
