# Generated by Django 4.1.4 on 2022-12-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_products_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.ManyToManyField(to='food.color'),
        ),
    ]
