# Generated by Django 4.1.4 on 2022-12-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0025_remove_products_color_products_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.ManyToManyField(related_name='col', to='food.color'),
        ),
    ]
