# Generated by Django 4.1.4 on 2022-12-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0026_alter_products_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='test',
        ),
    ]
