# Generated by Django 4.1.4 on 2022-12-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0035_rename_product_comment_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='products',
            new_name='product_comment',
        ),
    ]
