# Generated by Django 4.1.4 on 2022-12-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0037_rename_product_comment_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='comment_products',
        ),
    ]
