# Generated by Django 4.1.4 on 2022-12-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0038_rename_post_comment_comment_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_products',
            new_name='post',
        ),
    ]
