# Generated by Django 4.1.4 on 2022-12-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0040_rename_post_comment_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='comments',
            field=models.CharField(max_length=150, null=True, verbose_name='Comments'),
        ),
    ]
