# Generated by Django 4.1.4 on 2022-12-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0041_products_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product_name',
            new_name='post',
        ),
    ]
