# Generated by Django 4.1.4 on 2022-12-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0043_rename_post_comment_eating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='eating',
            new_name='post_product',
        ),
    ]
