# Generated by Django 4.1.4 on 2022-12-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0044_rename_eating_comment_post_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_product',
            new_name='post',
        ),
    ]
