# Generated by Django 4.1.4 on 2022-12-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0045_rename_post_product_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='comments',
        ),
    ]
