# Generated by Django 4.1.4 on 2022-12-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0048_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='products',
            new_name='product',
        ),
    ]
